default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['database_username'] %>
  password: <%= ENV['database_password'] %>
  pool: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
